name: Push and Pull Request Workflow

on:
  push:
    branches:
      - main
      - marc
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
    postgres_tests:
      runs-on: ubuntu-latest

      services:
        postgres:
          image: postgres:17
          env:
            POSTGRES_USER: marc
            POSTGRES_PASSWORD: blarg223
            POSTGRES_DB: ephemeraldb
          ports:
            - 5432:5432
          options: >-
            --health-cmd="pg_isready -U marc -d ephemeraldb"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=5
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install flake8
            pip install -r requirements.txt

        - name: Debug env (safe)
          run: |
            echo "USER=$POSTGRES_USER"
            echo "DB=$POSTGRES_DB"

        
        - name: Linting...
          run: flake8 src/ || true

        - name: Wait for Postgres
          run: |
            for i in {1..10}; do
              pg_isready -h 127.0.0.1 -p 5432 -U "$POSTGRES_USER" && break
              sleep 2
            done

        - name: Verify Schema
          env:
            POSTGRES_USER: marc
            POSTGRES_PASSWORD: blarg223
            POSTGRES_DB: ephemeraldb
            POSTGRES_HOST: 127.0.0.1
            POSTGRES_PORT: 5432
          run: |
            PGPASSWORD=$POSTGRES_PASSWORD psql \
              -h 127.0.0.1 \
              -p 5432 \
              -U $POSTGRES_USER \
              -d $POSTGRES_DB \
              -f src/docker/init-db.sql

        - name: Run postgres tests
          env:
            POSTGRES_USER: marc
            POSTGRES_PASSWORD: blarg223
            POSTGRES_DB: ephemeraldb
            POSTGRES_HOST: 127.0.0.1
            POSTGRES_PORT: 5432
          run: pytest src/databases/postgres/workflow_test.py -v
    chroma_tests:
      runs-on: ubuntu-latest
      env:
            PROFANITY_THRESHOLD: 0.7
            DISTANCE_THRESHOLD: 0.25
            DB_PATH: ./local_chromadb
            DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10.12'

        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run chroma tests
          run: pytest src/databases/chroma/chroma_tests.py -v
