name: Test PR 

on:
  push:
    branches:
      - main
      - marc
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
    postgres_tests:
      runs-on: ubuntu-latest

      services:
        postgres:
          image: postgres:17
          env:
            POSTGRES_USER: marc
            POSTGRES_PASSWORD: blarg223
            POSTGRES_DB: ephemeraldb
            POSTGRES_HOST: 127.0.0.1
            POSTGRES_PORT: 5432
          ports:
            - 5432:5432
          volumes:
            - ./src/databases/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
          options: >-
            --health-cmd="pg_isready -U marc"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=5
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install flake8
            pip install -r requirements.txt

        - name: Debug env (safe)
          run: |
            echo "USER=$POSTGRES_USER"
            echo "DB=$POSTGRES_DB"

        
        - name: Linting...
          run: flake8 src/ || true

        - name: Wait for Postgres
          run: |
            for i in {1..10}; do
              pg_isready -h 127.0.0.1 -p 5432 -U "$POSTGRES_USER" && break
              sleep 2
            done


        - name: Run postgres tests
          env:
            POSTGRES_USER: ${{ env.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ env.POSTGRES_DB }}
            POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
            POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
          run: pytest src/databases/postgres/workflow_test.py -v
